# from Johnson, Sean R., et al. "Computational scoring and experimental evaluation of enzymes generated by neural networks." Nature Biotechnology (2024): 1-10.
#install esm
# %pip -q install  git+https://github.com/facebookresearch/esm.git@e5e7b06b9a093706607c229ab1c5c9821806814d
pip install torch_geometric
pip install torch_scatter
pip install biotite
pip install fair-esm

#install hmmer, mafft, emboss, biotite, and sequence-models
# !apt-get -qq update > /dev/null
# !apt-get -qq install  hmmer mafft emboss > /dev/null
# !pip -q install  biotite pytest-datadir sequence-models > /dev/null

#install fasta3
# !wget https://github.com/wrpearson/fasta36/releases/download/v36.3.8i_14-Nov-2020/fasta-36.3.8i-linux64.tar.gz > /dev/null
# !tar xf fasta-36.3.8i-linux64.tar.gz > /dev/null
# !mv fasta-36.3.8i/bin/* /opt/bin
# !rm -r fasta*


#install protein_gibbs_sampler
# !git clone https://github.com/seanrjohnson/protein_gibbs_sampler > /dev/null
# !cd protein_gibbs_sampler ; git checkout 7de11ff63f7dca3cb52ef84109152ac8f988b7a0 2>&1 > /dev/null ; yes | pip install -q --no-dependencies . > /dev/null
# !yes | pip -q install  biopython~=1.79 pytest-datadir~=1.4.1 > /dev/null


#install ProteinMPNN
# !git clone https://github.com/dauparas/ProteinMPNN.git > /dev/null
# !cd ProteinMPNN ; git checkout 0a721279f6706478193f50dff9c1e5ff96214778 > /dev/null


### FROM ESM-IF example notebook https://github.com/facebookresearch/esm/blob/e5e7b06b9a093706607c229ab1c5c9821806814d/examples/inverse_folding/notebook.ipynb
# import torch
# def format_pytorch_version(version):
#   return version.split('+')[0]
#
# TORCH_version = torch.__version__
# TORCH = format_pytorch_version(TORCH_version)
#
# def format_cuda_version(version):
#   return 'cu' + version.replace('.', '')
#
# CUDA_version = torch.version.cuda
# CUDA = format_cuda_version(CUDA_version)
#
# !pip install -q torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html > /dev/null
# !pip install -q torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html > /dev/null
# !pip install -q torch-cluster -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html > /dev/null
# !pip install -q torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html > /dev/null
# !pip install -q torch-geometric > /dev/null
# ### END OF CODE FROM ESM-IF
